=== wk185031/amea-cbc_reporting-portal/src/main/resources/ActiveMQResources.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	xmlns:tns="http://www.jndi.activemq.authentic.com/ActiveMQResources"
	targetNamespace="http://www.jndi.activemq.authentic.com/ActiveMQResources"
	elementFormDefault="qualified" attributeFormDefault="unqualified"
	version="2.32">

	<element name="ActiveMQResources">
		<complexType>
			<sequence>
				<element name="secure" type="boolean" maxOccurs="1"
					minOccurs="1">
				</element>
				<element name="securityModule" type="tns:SecurityModule"
					maxOccurs="1" minOccurs="1">
				</element>
			</sequence>
		</complexType>
	</element>

	<complexType name="KeyStore">
		<sequence>
			<element name="type" type="string" maxOccurs="1" minOccurs="1"></element>
			<element name="path" type="string" maxOccurs="1"
				minOccurs="1">
			</element>
			<element name="storePassword" type="string" maxOccurs="1"
				minOccurs="1">
			</element>
			<element name="keyPassword" type="string" maxOccurs="1"
				minOccurs="0">
			</element>
			<element name="alias" type="string" maxOccurs="1"
				minOccurs="0">
			</element>
		</sequence>
	</complexType>

	<simpleType name="Protocol">
		<restriction base="string">
			<enumeration value="TLS" />
			<enumeration value="SSL" />
		</restriction>
	</simpleType>

	<simpleType name="Security">
		<restriction base="string">
			<enumeration value="ONE_WAY" />
			<enumeration value="TWO_WAY" />
			<enumeration value="NONE" />
		</restriction>
	</simpleType>

	<complexType name="SecurityModule">
		<sequence>
			<element name="protocol" type="tns:Protocol" maxOccurs="1"
				minOccurs="1">
			</element>
			<element name="security" type="tns:Security" maxOccurs="1"
				minOccurs="1"></element>
			<element name="trustStore" type="tns:KeyStore" maxOccurs="1"
				minOccurs="1">
			</element>
			<element name="keyStore" type="tns:KeyStore" maxOccurs="1"
				minOccurs="0">
			</element>
		</sequence>
	</complexType>
</schema>

=== wk185031/amea-cbc_reporting-portal/src/main/resources/ActiveMQResources.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<ActiveMQResources xmlns="http://www.jndi.activemq.authentic.com/ActiveMQResources" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.jndi.activemq.authentic.com/ActiveMQResources ./ActiveMQResources.xsd">
	<secure>true</secure>
    <securityModule>
        <protocol>TLS</protocol>
        <security>NONE</security>
        <trustStore>
        	<type>JKS</type>
            <path>C:/Tools/AppServers/apache-tomcat-8.0.12/conf/CMS-MQ.trusted.keystore</path>
            <storePassword>83CCB5D861536D1419FBB6086D875A1923322259AB1B448FE8559FD9ADADA4B4</storePassword>
            <keyPassword>F59A523CA5A1B215F5C101213A459614D763FDA1E212ADEFE9AB31838A9741D7</keyPassword>
            <alias>trust_activemq</alias>
        </trustStore>
        <keyStore>
        	<type>JKS</type>
            <path>C:/Tools/AppServers/apache-tomcat-8.0.12/conf/CMS-MQ.private.keystore</path>
            <storePassword>080DA93546F4F0614F1431C8D94200CE076F79561B6DEB216976324D9E24A1EE</storePassword>
            <keyPassword>2B8C034A29054927C5E4D6A14DDDC3262D9082CE9AB378A31A76BF49FC7185F3</keyPassword>
            <alias>private_cms-mq</alias>
        </keyStore>
    </securityModule>
</ActiveMQResources>
